"use client"

import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Link2, Maximize2, Minimize2, MoreHorizontal, Palette, Pin, Plus, Save, StickyNote, Trash2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { cn } from '@/lib/utils'

const initialNotes = [
  { id: 1, title: 'The morning routine', text: 'Start with the smallest move. Momentum compounds.', tone: 'yellow', x: 50, y: 48 },
  { id: 2, title: 'Focus window', text: '09:00 — 11:30\nNo meetings. Deep work only.', tone: 'paper', x: 310, y: 38 },
  { id: 3, title: 'Ship something', text: 'Small releases > perfect plans', tone: 'yellow', x: 650, y: 90 },
  { id: 4, title: 'Bug: missing deadline', text: 'To-do deadlines are not appearing after save. Reproduce in the To-Do popup.', tone: 'paper', x: 170, y: 330 },
] as const

type Note = (typeof initialNotes)[number]
type Point = { x: number; y: number }

export function DetectiveBoard() {
  const [notes, setNotes] = useState<Note[]>([...initialNotes])
  const [positions, setPositions] = useState<Record<number, Point>>({})
  const [sizes, setSizes] = useState<Record<number, Point>>({})
  const [selected, setSelected] = useState<number | null>(null)
  const [editing, setEditing] = useState<number | null>(null)
  const [draft, setDraft] = useState({ title: '', text: '' })
  const [connectMode, setConnectMode] = useState(false)
  const [connections, setConnections] = useState<[number, number][]>([[1, 3]])
  const [canvas, setCanvas] = useState({ width: 920, height: 600 })
  const [zoom, setZoom] = useState(1)
  const [expanded, setExpanded] = useState(false)
  const [colorOpen, setColorOpen] = useState(false)
  const [customColors, setCustomColors] = useState<Record<number, string>>({})
  const [referencePosition, setReferencePosition] = useState<Point>({ x: 560, y: 318 })
  const [resizing, setResizing] = useState<{ id: number; start: Point; size: Point } | null>(null)

  const points = useMemo(() => Object.fromEntries(notes.map((note) => [note.id, positions[note.id] ?? { x: note.x, y: note.y }])), [notes, positions]) as Record<number, Point>
  const referenceNode = { x: referencePosition.x, y: referencePosition.y }
  const allPoints = { ...points, 5: referenceNode }
  const paths = connections.flatMap(([from, to]) => { const a = allPoints[from]; const b = allPoints[to]; return a && b ? [`M ${a.x + 100} ${a.y + 62} C ${a.x + 260} ${a.y - 30}, ${b.x - 60} ${b.y + 150}, ${b.x + 100} ${b.y + 62}`] : [] })
  const distance = (touches: TouchList) => Math.hypot(touches[0].clientX - touches[1].clientX, touches[0].clientY - touches[1].clientY)
  const [pinch, setPinch] = useState<{ distance: number; zoom: number } | null>(null)
  const zoomIn = () => setZoom((value) => Math.min(2.5, value + 0.1))
  const zoomOut = () => setZoom((value) => Math.max(0.5, value - 0.1))
  const selectNote = (id: number) => { if (connectMode && selected !== null && selected !== id) { setConnections((items) => [...items, [selected, id]]) ; setSelected(null); return }; setSelected(id) }
  const addNote = () => { const id = Math.max(0, ...notes.map((note) => note.id)) + 1; const note = { id, title: 'New note', text: 'Add your idea here.', tone: 'yellow', x: 90 + notes.length * 34, y: 110 + notes.length * 24 } as Note; setNotes((items) => [...items, note]); setSelected(id); setEditing(id); setDraft({ title: note.title, text: note.text }) }
  const deleteNote = () => { const id = editing ?? selected; if (id === null || id === undefined) return; setNotes((items) => items.filter((note) => note.id !== id)); setConnections((items) => items.filter(([a, b]) => a !== id && b !== id)); setEditing(null); setSelected(null) }
  return <div className="relative overflow-hidden rounded-2xl border border-border/70 bg-zinc-950 px-5 py-6 shadow-2xl sm:px-8">
    <div className="pointer-events-none absolute inset-0 board-dots opacity-60" />
    <div className="relative z-10 flex items-start justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground"><Pin className="size-3" /> Board / 01</p><div className="flex items-center gap-2"><h2 className="text-3xl font-semibold tracking-tight">Planning Board</h2><span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.14em] text-amber-200" title="This board is still in development">Beta</span></div><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">Move notes freely and connect as many ideas as you need.</p></div><div className="flex items-center gap-2"><Button variant="outline" size="icon" aria-label="Toggle fullscreen canvas" onClick={() => setExpanded(!expanded)}>{expanded ? <Minimize2 /> : <Maximize2 />}</Button><Button variant="outline" size="icon" aria-label="Board options"><MoreHorizontal /></Button></div></div>
    <div onWheel={(event) => { if (event.ctrlKey || event.metaKey) { event.preventDefault(); setZoom((value) => Math.min(2.5, Math.max(0.5, value - event.deltaY * 0.002))) } }} onTouchStart={(event) => event.touches.length === 2 && setPinch({ distance: distance(event.touches), zoom })} onTouchMove={(event) => { if (event.touches.length === 2 && pinch) { event.preventDefault(); setZoom(Math.min(2.5, Math.max(0.5, pinch.zoom * distance(event.touches) / pinch.distance))) } }} onTouchEnd={() => setPinch(null)} className={cn('relative mt-8 min-h-[420px] overflow-auto rounded-xl border border-border/40 bg-background/20', expanded && 'min-h-[calc(100vh-12rem)]')} style={{ height: expanded ? 'calc(100vh - 12rem)' : Math.max(640, canvas.height * zoom) }}>
      <div className="relative board-dots" style={{ width: canvas.width * zoom, height: canvas.height * zoom, touchAction: 'none' }}><div className="absolute left-0 top-0" style={{ width: canvas.width, height: canvas.height, transform: `scale(${zoom})`, transformOrigin: 'top left' }}>
        <svg className="pointer-events-none absolute inset-0" width={canvas.width} height={canvas.height} aria-hidden="true">{paths.map((d, i) => <path key={i} d={d} fill="none" stroke="oklch(.62 0 0)" strokeDasharray="9 10" strokeLinecap="round" strokeWidth="3" />)}</svg>
        {notes.map((note, index) => { const point = points[note.id]; const size = sizes[note.id] ?? { x: 240, y: 180 }; return <motion.div key={note.id} drag dragMomentum={false} dragConstraints="parent" onDragEnd={(_, info) => setPositions((items) => ({ ...items, [note.id]: { x: point.x + info.offset.x / zoom, y: point.y + info.offset.y / zoom } }))} onClick={() => selectNote(note.id)} onDoubleClick={() => { setEditing(note.id); setDraft({ title: note.title, text: note.text }) }} className={cn('absolute z-10 cursor-grab overflow-hidden rounded-sm border p-5 text-left shadow-2xl active:cursor-grabbing', note.tone === 'yellow' ? 'border-[#b8a94d]/40 bg-[#c9bd61] text-zinc-950' : note.tone === 'blue' ? 'border-sky-300/40 bg-sky-400 text-slate-950' : note.tone === 'green' ? 'border-emerald-300/40 bg-emerald-400 text-emerald-950' : 'border-border bg-card/90 text-foreground')} style={{ left: point.x, top: point.y, width: size.x, height: size.y, ...(customColors[note.id] ? { backgroundColor: customColors[note.id] } : {}) }}><span className="mb-5 flex items-center justify-between text-[10px] font-semibold uppercase tracking-[0.18em] opacity-60"><StickyNote className="size-3" /> {String(index + 1).padStart(2, '0')}</span><span className="block font-mono text-sm font-semibold">{note.title}</span><span className="mt-3 block whitespace-pre-line text-xs leading-5 opacity-75">{note.text}</span><span aria-label="Resize note" onPointerDown={(event) => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); setResizing({ id: note.id, start: { x: event.clientX, y: event.clientY }, size }) }} onPointerMove={(event) => { if (resizing?.id === note.id) setSizes((items) => ({ ...items, [note.id]: { x: Math.max(170, resizing.size.x + (event.clientX - resizing.start.x) / zoom), y: Math.max(120, resizing.size.y + (event.clientY - resizing.start.y) / zoom) } })) }} onPointerUp={() => setResizing(null)} className="absolute bottom-1 right-1 size-4 cursor-se-resize rounded-sm bg-foreground/30" /></motion.div> })}
        <motion.div drag dragMomentum={false} dragConstraints="parent" onDragEnd={(_, info) => setReferencePosition((point) => ({ x: point.x + info.offset.x / zoom, y: point.y + info.offset.y / zoom }))} onClick={(event) => { event.stopPropagation(); selectNote(5) }} className={cn('absolute z-10 w-52 overflow-hidden rounded-lg border border-border bg-card/80 shadow-2xl backdrop-blur-xl sm:w-60', selected === 5 && 'ring-2 ring-foreground')} style={{ left: referencePosition.x, top: referencePosition.y }}><img src="/bug-reference.png" alt="Bug reference showing a missing deadline field" className="h-28 w-full object-cover" /><div className="p-4"><p className="text-sm font-semibold">Note 4 reference</p><p className="mt-1 text-xs text-muted-foreground">Bug evidence</p></div></motion.div>
      </div><div className="fixed bottom-4 left-1/2 z-[60] flex h-12 w-max max-w-[calc(100vw-2rem)] -translate-x-1/2 scale-100 items-center gap-1 overflow-x-auto rounded-2xl border border-border bg-card/90 p-1.5 shadow-2xl backdrop-blur-2xl"><Button size="sm" variant="ghost" onClick={addNote}><Plus data-icon="inline-start" />Add Note</Button><Button size="sm" variant={connectMode ? 'secondary' : 'ghost'} onClick={() => { setConnectMode(!connectMode); setSelected(null) }}><Link2 data-icon="inline-start" />{connectMode ? 'Done' : 'Connect'}</Button><Button size="sm" variant="ghost" onClick={zoomOut} aria-label="Zoom out">−</Button><span className="min-w-12 text-center text-xs tabular-nums">{Math.round(zoom * 100)}%</span><Button size="sm" variant="ghost" onClick={zoomIn} aria-label="Zoom in">+</Button><div className="relative"><Button size="sm" variant="ghost" onClick={() => setColorOpen((open) => !open)}><Palette data-icon="inline-start" />Change Color</Button>{colorOpen && <div className="absolute bottom-full left-1/2 mb-2 flex -translate-x-1/2 gap-2 rounded-xl border border-border bg-card p-2 shadow-2xl"><label className="flex items-center gap-2 rounded-md border border-border bg-background px-2 py-1 text-xs"><span>Custom</span><input type="color" aria-label="Pick custom note color" value={selected !== null ? customColors[selected] ?? '#c9bd61' : '#c9bd61'} onChange={(event) => { if (selected !== null && selected !== 5) setCustomColors((items) => ({ ...items, [selected]: event.target.value })) }} className="size-7 cursor-pointer border-0 bg-transparent p-0" /></label><span className="sr-only">Choose note color</span>{(['yellow', 'paper', 'blue', 'green'] as const).map((tone) => <button key={tone} type="button" aria-label={`Set ${tone} note color`} onClick={() => { if (selected !== null && selected !== 5) setNotes((items) => items.map((note) => note.id === selected ? { ...note, tone } : note)); setColorOpen(false) }} className={cn('size-7 rounded-full border-2 border-background ring-1 ring-border', tone === 'yellow' && 'bg-[#c9bd61]', tone === 'paper' && 'bg-card', tone === 'blue' && 'bg-sky-400', tone === 'green' && 'bg-emerald-400')} />)}</div>}</div>{selected !== null && <Button size="sm" variant="ghost" className="text-destructive" onClick={deleteNote}><Trash2 data-icon="inline-start" />Delete note</Button>}</div>
    </div>
    <Dialog open={editing !== null} onOpenChange={(open) => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Edit note</DialogTitle><DialogDescription>Update this note without leaving the board.</DialogDescription></DialogHeader><div className="grid gap-3"><input aria-label="Note title" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="h-10 rounded-md border border-input bg-background px-3 text-sm" /><textarea aria-label="Note description" value={draft.text} onChange={(event) => setDraft({ ...draft, text: event.target.value })} className="min-h-28 rounded-md border border-input bg-background px-3 py-2 text-sm" /></div><DialogFooter><Button variant="destructive" onClick={deleteNote}><Trash2 data-icon="inline-start" />Delete note</Button><Button onClick={() => { if (editing !== null) setNotes((items) => items.map((note) => note.id === editing ? { ...note, title: draft.title || 'Untitled note', text: draft.text || 'No description yet.' } : note)); setEditing(null) }}><Save data-icon="inline-start" />Save changes</Button></DialogFooter></DialogContent></Dialog>

  </div>
  </div>
}

export const PlanningBoard = DetectiveBoard
